### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by GitHub-23666** [yangxy/GPEN#105]
After Git pull GPEN does not work anymore. It always comes:

```
Traceback (most recent call last):
  File "face_enhancement.py", line 148, in <module>
    img, orig_faces, enhanced_faces = faceenhancer.process(im)
  File "face_enhancement.py", line 87, in process
    ef = self.facegan.process(of)
  File "E:\GPEN\face_model\face_gan.py", line 42, in process
    out, __ = self.model(img_t)
ValueError: not enough values to unpack (expected 2, got 1)

```

GPEN executed normally with:
`python face_enhancement.py --use_cuda --model GPEN-BFR-512 --indir "XYZ" --outdir "XYZ"`

**Comment by yangxy** [comment]
Fixed.
