### ISSUE TITLE
Help for installation GPEN on ubuntu 22.04

### ISSUE THREAD

**Issue by gravitydeep** [yangxy/GPEN#138]
Hello, I have been trying to install gpen on ubuntu 22.04 for several times but I always get errors so as I managed to install gfpgan I tried the same method as the tuto found on youtube https://www.youtube.com/watch?v=9fJWuwD_nxE 
but without success.
Is there anyone who has time to help me because I am a beginner?

Here is what I tried :

== Download ==

git clone https://github.com/yangxy/GPEN.git
cd GPEN/

== Virtual python environment ==

conda create --name gpen python=3.9
conda activate gpen

== set up the environment  ==

pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
pip install -r requirements.txt

and download  pre-trained models in weights

**Comment by yangxy** [comment]
Can you paste the error log here?

**Comment by gravitydeep** [comment]
hello and thank you for answering me so when I try the first command like on your git it gives

(gpen) cedric@apache:~/LAB/GPEN$ python demo.py --task FaceEnhancement --model GPEN-BFR-512 --in_size 512 --channel_multiplier 2 --narrow 1 --use_sr --sr_scale 4 --use_cuda --save_face --indir examples/imgs --outdir examples/outs-bfr

Traceback (most recent call last):
  File "/home/cedric/LAB/GPEN/demo.py", line 14, in <module>
    from face_enhancement import FaceEnhancement
  File "/home/cedric/LAB/GPEN/face_enhancement.py", line 11, in <module>
    from face_model.face_gan import FaceGAN
  File "/home/cedric/LAB/GPEN/face_model/face_gan.py", line 13, in <module>
    from gpen_model import FullGenerator, FullGenerator_SR
  File "/home/cedric/LAB/GPEN/face_model/gpen_model.py", line 16, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/cedric/LAB/GPEN/face_model/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/cedric/LAB/GPEN/face_model/op/fused_act.py", line 13, in <module>
    fused = load(
  File "/home/cedric/miniconda3/envs/gpen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "/home/cedric/miniconda3/envs/gpen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/cedric/miniconda3/envs/gpen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1443, in _write_ninja_file_and_build_library
    check_compiler_abi_compatibility(compiler)
  File "/home/cedric/miniconda3/envs/gpen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 300, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/home/cedric/miniconda3/envs/gpen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 257, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/home/cedric/miniconda3/envs/gpen/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/cedric/miniconda3/envs/gpen/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.

**Comment by yangxy** [comment]
How about your environment settings? such as cuda, gcc, pytorch, driver, and so on. It seems that gcc is not working correctly

**Comment by gravitydeep** [comment]
Proccessor Intel® Core™ i7-10870H CPU @ 2.20GHz × 16
memoire 16 Gio

hello after researching  i m install 
conda install -c conda-forge cudatoolkit-dev
build-essantial

and I had too recent version of gcc (11.2) so I installed version 9 and 10 to switch( i'm switch on 10 )

ok there is some progress but new error

python demo.py --task FaceEnhancement --model GPEN-BFR-512 --in_size 512 --channel_multiplier 2 --narrow 1 --use_sr --sr_scale 4 --use_cuda --save_face --indir examples/imgs --outdir examples/outs-bfr

sr failed: CUDA out of memory. Tried to allocate 1.44 GiB (GPU 0; 5.81 GiB total capacity; 2.39 GiB already allocated; 1.02 GiB free; 2.86 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
0 Solvay_conference_1927.png

nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   37C    P8    13W /  N/A |    116MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2125      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      2422    C+G   ...ome-remote-desktop-daemon      107MiB |
+-----------------------------------------------------------------------------+

**Comment by gravitydeep** [comment]
Proccessor Intel® Core™ i7-10870H CPU @ 2.20GHz × 16
memoire 16 Gio

I didn't check if it worked but after deleting all the outs and restarting the command I realized that it worked but I still have this error

sr failed: CUDA out of memory. Tried to allocate 1.44 GiB (GPU 0; 5.81 GiB total capacity; 2.39 GiB already allocated; 1.02 GiB free; 2.86 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by gravitydeep** [comment]
ok i tried again and i didn't get this memory error i don't understand but ok .....

I wanted to ask you if it was possible to separate the results in different folders, for example compared folder, cropped and image restored? if yes, how should I do it?

**Comment by yangxy** [comment]
It seems the error is OOM due to sr. It doesn't matter that much. 
Please try ``--tile`` to address it. See #129. Alternatively, disable ``--use_sr``.

**Comment by yangxy** [comment]
> 



> ok i tried again and i didn't get this memory error i don't understand but ok .....
> 
> I wanted to ask you if it was possible to separate the results in different folders, for example compared folder, cropped and image restored? if yes, how should I do it?
> 
> and what is it for Train GPEN for BFR with 4 GPUs ?

Please read the code in ``demo.py``, and revise it accordingly.
