### ISSUE TITLE
from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d

### ISSUE THREAD

**Issue by keetsky** [yangxy/GPEN#14]
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

  import err when import ops

**Comment by keetsky** [comment]
error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.\nninja: build stopped: subcommand failed.\n'

**Comment by keetsky** [comment]
mportError: No module named 'fused'

**Comment by yangxy** [comment]
Please check the README.md carefully and make sure you have installed python==3.7.4, pytorch==1.7.0, cuda==10.2.89, NVIDIA driver==460.73.01, gcc==7.5.0. You should also install packages listed in the requirements.txt.

**Comment by keetsky** [comment]
Thanks.

**Comment by song201216** [comment]
**Hello, I have also encountered the same mistake with you. How do you solve it?**

D:\Anaconda3\envs\torch18\python.exe E:/code/GPEN-main/face_inpainting.py
D:\Anaconda3\envs\torch18\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
��Ϣ: ���ṩ��ģʽ�޷��ҵ��ļ���
Traceback (most recent call last):
  File "E:/code/GPEN-main/face_inpainting.py", line 13, in <module>
    from face_model.face_gan import FaceGAN
  File "E:\code\GPEN-main\face_model\face_gan.py", line 13, in <module>
    from model import FullGenerator
  File "E:\code\GPEN-main\face_model\model.py", line 15, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "E:\code\GPEN-main\face_model\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "E:\code\GPEN-main\face_model\op\fused_act.py", line 10, in <module>
    fused = load(
  File "D:\Anaconda3\envs\torch18\lib\site-packages\torch\utils\cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "D:\Anaconda3\envs\torch18\lib\site-packages\torch\utils\cpp_extension.py", line 1317, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Anaconda3\envs\torch18\lib\site-packages\torch\utils\cpp_extension.py", line 1699, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "D:\Anaconda3\envs\torch18\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'
