### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

### ISSUE THREAD

**Issue by javierherrera1996** [yangxy/GPEN#143]
i don't knwo if is my problem or the path are corrupted. Help

python demo.py --task FaceEnhancement --model GPEN-BFR-512 --in_size 512 --channel_multiplier 2 --narrow 1 --use_sr --sr_scale 4 --use_cuda --save_face --indir examples/imgs --outdir examples/outs-bfr

Traceback (most recent call last):
  File "demo.py", line 97, in <module>
    processer = FaceEnhancement(args, in_size=args.in_size, model=args.model, use_sr=args.use_sr, device='cuda' if args.use_cuda else 'cpu')
  File "/home/jupyter/Cedulas-Fraude/Notebooks/cv_fraude_extraccion/utils/GPEN/face_enhancement.py", line 18, in __init__
    self.facegan = FaceGAN(base_dir, in_size, out_size, model, args.channel_multiplier, args.narrow, args.key, device=device)
  File "/home/jupyter/Cedulas-Fraude/Notebooks/cv_fraude_extraccion/utils/GPEN/face_model/face_gan.py", line 24, in __init__
    self.load_model(channel_multiplier, narrow)
  File "/home/jupyter/Cedulas-Fraude/Notebooks/cv_fraude_extraccion/utils/GPEN/face_model/face_gan.py", line 31, in load_model
    pretrained_dict = torch.load(self.mfile, map_location=torch.device('cpu'))
  File "/opt/conda/envs/fraude/lib/python3.7/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/conda/envs/fraude/lib/python3.7/site-packages/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

**Comment by lmvgjp** [comment]
hi, I have the same problem when trying to use my trainned model...did you solve it?
Thanks

**Comment by ls20vip** [comment]
嗨，我在尝试使用我的训练模型时遇到了同样的问题......你解决了吗？
谢谢
