### ISSUE TITLE
Error when trying to run it

### ISSUE THREAD

**Issue by Yishaqel** [yangxy/GPEN#22]
I have tried to install it but when I try to launch the python file I get this error on Windows 10.

`(base) C:\better\GPEN>python face_enhancement.py
Traceback (most recent call last):
  File "face_enhancement.py", line 12, in <module>
    from retinaface.retinaface_detection import RetinaFaceDetection
  File "C:\better\GPEN\retinaface\retinaface_detection.py", line 6, in <module>
    import torch
  File "C:\Users\hadex\anaconda3\lib\site-packages\torch\__init__.py", line 123, in <module>
    raise err
OSError: [WinError 127] No se encontró el proceso especificado. Error loading "C:\Users\hadex\anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.`

**Comment by yangxy** [comment]
> I have tried to install it but when I try to launch the python file I get this error on Windows 10.
> 
> `(base) C:\better\GPEN>python face_enhancement.py Traceback (most recent call last): File "face_enhancement.py", line 12, in <module> from retinaface.retinaface_detection import RetinaFaceDetection File "C:\better\GPEN\retinaface\retinaface_detection.py", line 6, in <module> import torch File "C:\Users\hadex\anaconda3\lib\site-packages\torch\__init__.py", line 123, in <module> raise err OSError: [WinError 127] No se encontró el proceso especificado. Error loading "C:\Users\hadex\anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.`

It seems that you hadn't installed PyTorch correctly.
