### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chenruolin2019** [yangxy/GPEN#27]
Traceback (most recent call last):
  File "D:\GPEN-main\face_enhancement.py", line 13, in <module>
    from face_model.face_gan import FaceGAN
  File "D:\GPEN-main\face_model\face_gan.py", line 13, in <module>
    from model import FullGenerator
  File "D:\GPEN-main\face_model\model.py", line 15, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "D:\GPEN-main\face_model\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "D:\GPEN-main\face_model\op\fused_act.py", line 10, in <module>
    fused = load(
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 1122, in load
    return _jit_compile(name,
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 1367, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 1751, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "D:\Anaconda3\envs\torch\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'

**Comment by chenruolin2019** [comment]
How to deal with?

**Comment by CyberGodSA** [comment]
Try to update torch to version >= 1.3.1

**Comment by song201216** [comment]
Hello, author, have you solved this problem? I have the same problem as you. Thank you.

**Comment by yangxy** [comment]
> Hello, author, have you solved this problem? I have the same problem as you. Thank you.

It seems the libraries are not being built well. Please try to update torch(>=1.7), gcc(>=5.2), cuda(>=10.0) and nvidia driver(>440).
