### ISSUE TITLE
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Hbroda** [yangxy/GPEN#29]
Hi there!
When I try to apply the command "python face_enhancement.py" I get the following error.

(gpen) F:\Anaconda3\GPEN-main>python face_enhancement.py
F:\Anaconda3\envs\gpen\lib\site-packages\torch\utils\cpp_extension.py:274: UserWarning: Error checking compiler version for cl: [WinError 2] El sistema no puede encontrar el archivo especificado
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
INFORMACIÓN: no se pudo encontrar ningún archivo para los patrones dados.
Traceback (most recent call last):
  File "face_enhancement.py", line 13, in <module>
    from face_model.face_gan import FaceGAN
  File "F:\Anaconda3\GPEN-main\face_model\face_gan.py", line 13, in <module>
    from model import FullGenerator
  File "F:\Anaconda3\GPEN-main\face_model\model.py", line 15, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "F:\Anaconda3\GPEN-main\face_model\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "F:\Anaconda3\GPEN-main\face_model\op\fused_act.py", line 14, in <module>
    os.path.join(module_path, 'fused_bias_act_kernel.cu'),
  File "F:\Anaconda3\envs\gpen\lib\site-packages\torch\utils\cpp_extension.py", line 980, in load
    keep_intermediates=keep_intermediates)
  File "F:\Anaconda3\envs\gpen\lib\site-packages\torch\utils\cpp_extension.py", line 1185, in _jit_compile
    with_cuda=with_cuda)
  File "F:\Anaconda3\envs\gpen\lib\site-packages\torch\utils\cpp_extension.py", line 1276, in _write_ninja_file_and_build_library
    with_cuda=with_cuda)
  File "F:\Anaconda3\envs\gpen\lib\site-packages\torch\utils\cpp_extension.py", line 1656, in _write_ninja_file_to_build_library
    with_cuda=with_cuda)
  File "F:\Anaconda3\envs\gpen\lib\site-packages\torch\utils\cpp_extension.py", line 1758, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "F:\Anaconda3\envs\gpen\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "F:\Anaconda3\envs\gpen\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

![Sin título](https://user-images.githubusercontent.com/87241145/127719046-7c06826a-8127-4419-b28c-c923d9491853.png)
Any idea why this happens to me? Do I need to install something?

**Comment by song201216** [comment]
You may refer to this article。https://blog.csdn.net/m0_37759119/article/details/90730276
