### ISSUE TITLE
Traceback (most recent call last):   File "face_enhancement.py", line 12, in <module>     from retinaface.retinaface_detection import RetinaFaceDetection ModuleNotFoundError: No module named 'retinaface.retinaface_detection'

### ISSUE THREAD

**Issue by onlinehuazai** [yangxy/GPEN#37]
Traceback (most recent call last):
  File "face_enhancement.py", line 12, in <module>
    from retinaface.retinaface_detection import RetinaFaceDetection
ModuleNotFoundError: No module named 'retinaface.retinaface_detection'

**Comment by yangxy** [comment]
It seems CUDA was not installed correctly. Please reinstall CUDA.

You can alternatively run "find / -name libcudart.so*". If the lib was already available in your machine, try to create a softlink to /usr/lib64/libcudart.so.10.0
