### ISSUE TITLE
ImportError: No module named 'fused'

### ISSUE THREAD

**Issue by suicycle** [yangxy/GPEN#69]
Hello, 
I am on Win 10. I installed GPEN via Anaconda 3. 
This is the error I am getting : 

(GPEN) C:\Users\PC\Desktop\GPEN>python face_enhancement.py --model GPEN-BFR-512 --size 512 --channel_multiplier 2 --narrow 1 --use_sr --indir examples/imgs --outdir examples/outs-BFR
Traceback (most recent call last):
  File "face_enhancement.py", line 14, in <module>
    from face_model.face_gan import FaceGAN
  File "C:\Users\PC\Desktop\GPEN\face_model\face_gan.py", line 13, in <module>
    from model import FullGenerator
  File "C:\Users\PC\Desktop\GPEN\face_model\model.py", line 16, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "C:\Users\PC\Desktop\GPEN\face_model\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\PC\Desktop\GPEN\face_model\op\fused_act.py", line 14, in <module>
    os.path.join(module_path, 'fused_bias_act_kernel.cu'),
  File "C:\Users\PC\anaconda3\envs\GPEN\lib\site-packages\torch\utils\cpp_extension.py", line 997, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\PC\anaconda3\envs\GPEN\lib\site-packages\torch\utils\cpp_extension.py", line 1213, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\PC\anaconda3\envs\GPEN\lib\site-packages\torch\utils\cpp_extension.py", line 1560, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "C:\Users\PC\anaconda3\envs\GPEN\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'

I have tried to clean the tmp/torch_extensions/ folder but am still getting the same error. I don't know what else I should do.

**Comment by DJMeng** [comment]
maybe you can upgrade the version of gcc to 3.9+

**Comment by yangxy** [comment]
GPEN can now work on a WIndows machine. Please have a try.
