### ISSUE TITLE
Ninja -v returned non zero exit - Ubuntu 20.04 with cuda

### ISSUE THREAD

**Issue by cheetahfight** [yangxy/GPEN#91]
While trying to do the run face_enhance

```
/hdd/simple/gpen$ python3 face_enhancement.py --model GPEN-BFR-512 --size 512 --channel_multiplier 2 --narrow 1 --use_cuda --indir /input --outdir examples/outs-BFR
Traceback (most recent call last):
  File "/home/simple/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1536, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:
```

**Comment by cheetahfight** [comment]
Issue solved by changing cuda paths in .bashrc.
